version: '2'
services:
    jwtdemo-app:
        image: jwtdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jwtdemo-mysql:3306/jwtdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 2345:2345
    jwtdemo-mysql:
        extends:
            file: mysql.yml
            service: jwtdemo-mysql
